"""Corrigindo erro na tabela Providers

Revision ID: 0ada6a6e33b5
Revises: 021c4d96b26d
Create Date: 2026-04-29 20:20:08.671315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ada6a6e33b5'
down_revision = '021c4d96b26d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
